name: cath_gen
channels:
  - defaults
  - conda-forge
  - bioconda
  - pytorch
  - huggingface
  - https://levinthal:paradox@conda.graylab.jhu.edu
dependencies:
  - pip:
      - biopython==1.79
      - deepspeed==0.5.8
      - dm-tree==0.1.6
      - ml-collections==0.1.0
      - numpy==1.21.2
      - PyYAML==5.4.1
      - requests==2.26.0
      - scipy==1.7.1
      - tqdm==4.62.2
      - typing-extensions==3.10.0.2
      - pytorch_lightning==1.5.10
      - git+https://github.com/NVIDIA/dllogger.git
      - nvidia-pyindex
      - beautifulsoup4
      - fair-esm
      - wandb
  - intel-openmp=2021.4.0
  - cudatoolkit=11.3
  - matplotlib
  - huggingface::transformers
  - pytorch::pytorch=1.10.0
  - conda-forge::python=3.7
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  - conda-forge::openmm=7.5.1
  - conda-forge::pdbfixer
  - conda-forge::easydict
  - conda-forge::ipython
  - conda-forge::scikit-learn
  - conda-forge::cudatoolkit-dev==11.*
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - bioconda::aria2
  - https://levinthal:paradox@conda.graylab.jhu.edu::pyrosetta
