model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8

data:
  data_module:
    data_loaders:
      num_workers: 8
  common:
    max_recycling_iters: 0

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000