model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  template:
    enabled: false
  extra_msa:
    enabled: false

data:
  data_module:
    data_loaders:
      batch_size: 2