model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8

data:
  data_module:
    data_loaders:
      num_workers: 8
  train:
    loop_type: '3'
  eval:
    loop_type: '3'
  predict:
    loop_type: '3'

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000