model:
  evoformer_stack:
    no_blocks: 8
    seq_dropout: 0.125
  structure_module:
    no_blocks: 8
  inverse_evoformer_stack:
    no_blocks: 8

loss:
  tm:
    weight: 0.01
    enabled: True 
  seqs:
    weight: 0.0

globals:
  c_m: 1024
  c_z: 128
  c_m_structure: 384
  c_z_structure: 128
    
data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.0005

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000