model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
    mask_loop_type: 0.0
  template:
    enabled: false
  extra_msa:
    enabled: false

data:
  train:
    crop_size: 320
  common:
    loop_type: antibody

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 10000
  decay_every_n_steps: 1000

globals:
  loop_only: true