model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  input_embedder:
    tf_dim: 21

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 0
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 2000