model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 1000
  start_decay_after_n_steps: 5000
  decay_every_n_steps: 1000