model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  residue_emb:
    enabled: true
    usage: replace
data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 2000
  start_decay_after_n_steps: 20000
  decay_every_n_steps: 2000