model:
  evoformer_stack:
    no_blocks: 32
    c_s: 1024
  structure_module:
    no_blocks: 32
    c_m: 384
    c_z: 128
  input_embedder:
    c_m: 1024
  residue_emb:
    enabled: true
    usage: replace
  residue_attn:
    enabled: true
    
data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.001

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000