model:
  evoformer_stack:
    no_blocks: 48
  structure_module:
    no_blocks: 48
  inverse_evoformer_stack:
    no_blocks: 16
    
  residue_emb:
    enabled: true
    usage: replace
  residue_attn:
    enabled: true

globals:
  c_m: 1024
  c_z: 128
  c_z_structure: 128
  c_m_structure: 384

data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.0005

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000
