model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  residue_emb:
    enabled: true
    usage: replace
  residue_attn:
    enabled: true
    
data:
  data_module:
    data_loaders:
      num_workers: 8

optimizer:
  lr: 0.005

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000