model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  inverse_evoformer_stack:
    no_blocks: 16
  residue_emb:
    enabled: true
    usage: replace
  residue_attn:
    enabled: true

globals:
  c_m: 1024
  c_z: 128
  c_z_structure: 128
  c_m_structure: 384
  lm_name: esm2_t36_3B_UR50D

loss:
  tm:
    enabled: true
    weight: 0.01
  supervised_chi:
    weight: 0.0

data:
  data_module:
    data_loaders:
      batch_size: 16
      num_workers: 10
  eval:
    crop: true
    crop_size: 384

optimizer:
  lr: 0.0005

# correspond to 48 node parallel
# we need to divise by 48
# 128000/48 = 2666
# 2666/16 = 166
scheduler:
  warmup_no_steps: 165
  start_decay_after_n_steps: 1650
  decay_every_n_steps: 165
