model:
  evoformer_stack:
    no_blocks: 8
  structure_module:
    no_blocks: 8
  inverse_evoformer_stack:
    no_blocks: 8
  residue_emb:
    enabled: true
    usage: replace
  residue_attn:
    enabled: true

globals:
  inv_c_m: 256
  inv_c_z: 128
  inv_c_m_structure: 384
  inv_c_z_structure: 128
  lm_name: esm2_t36_3B_UR50D

loss:
  tm:
    enabled: true
    weight: 0.01
  supervised_chi:
    weight: 0.0

data:
  data_module:
    data_loaders:
      num_workers: 10

optimizer:
  lr: 0.0005

scheduler:
  warmup_no_steps: 5000
  start_decay_after_n_steps: 50000
  decay_every_n_steps: 5000
